server:
  port: 8123
  servlet:
    context-path: /api
spring:
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#        #sse:
#        #  connections:
#        #    server1:
#        #      url: http://localhost:8127
  application:
    name: hive-ai-agent
  profiles:
    active: local
logging:
  level:
    root: INFO
    org.springframework.ai.vectorstore: WARN
# springdoc-openapi 接口文档配置
springdoc:
  swagger-ui:
    path: /shturl.cc/e2qXW
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hive.hiveaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
